version: '3.8'

services:
  test_app:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - DB_HOST=test_db
      - DB_NAME=test_EM2_2dz
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_PORT=5432
      - REDIS_HOST=test_redis
      - DEBUG=True
      - TESTING=True
      - PYTHONPATH=/app
    depends_on:
      - test_db
      - test_redis

  test_db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_EM2_2dz

  test_redis:
    image: redis:7-alpine