services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=EM2_2dz
      - DB_USER=postgres
      - DB_PASS=postgres
      - DEBUG = True
      - LOG_LEVEL = DEBUG
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: EM2_2dz
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
volumes:
  postgres_data:
  redis_data: